# Generated by Django 6.0.7 on 2026-07-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('profissionais', '0002_alter_profissional_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('site', 'Site'), ('instagram', 'Instagram'), ('email', 'E-mail')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_contato', to='empresas.empresa')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_contato', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Evento de contato',
                'verbose_name_plural': 'Eventos de contato',
                'ordering': ['-criado_em'],
            },
        ),
    ]
