# Generated by Django 6.0.7 on 2026-07-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('estado', models.CharField(default='MG', max_length=2)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('populacao', models.PositiveIntegerField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cidades/')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
    ]
