# Generated by Django 6.0.7 on 2026-07-23 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0002_ampliar_cadastro_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='cidade ativa'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criada em'),
            preserve_default=False,
        ),
    ]
