# Generated by Django 6.0.7 on 2026-07-25 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_usuario'),
        ('planos', '0002_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_financeiros', to='planos.assinatura')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_financeiros', to='empresas.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_financeiros', to='planos.plano')),
            ],
            options={
                'verbose_name': 'Pedido Financeiro',
                'verbose_name_plural': 'Pedidos Financeiros',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('manual', 'Manual')], default='pix', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_transacao', models.CharField(blank=True, max_length=200)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.pedidofinanceiro')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ('-criado_em',),
            },
        ),
    ]
