# Generated by Django 6.0.7 on 2026-07-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_usuario'),
        ('financeiro', '0001_initial'),
        ('profissionais', '0003_profissional_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidofinanceiro',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_financeiros', to='profissionais.profissional'),
        ),
        migrations.AlterField(
            model_name='pedidofinanceiro',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_financeiros', to='empresas.empresa'),
        ),
    ]
