# Generated by Django 6.0.7 on 2026-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_pedidofinanceiro_profissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/'),
        ),
    ]
