# Generated by Django 6.0.7 on 2026-07-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('endereco', models.CharField(blank=True, max_length=220)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True)),
                ('site', models.URLField(blank=True)),
                ('horario', models.CharField(blank=True, max_length=180)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('destaque', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='categorias.categoria')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='cidades.cidade')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-destaque', 'nome_fantasia'],
                'constraints': [models.UniqueConstraint(fields=('cidade', 'slug'), name='empresa_slug_unico_por_cidade')],
            },
        ),
    ]
