# Generated by Django 6.0.7 on 2026-07-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='empresas/galeria/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Foto da empresa',
                'verbose_name_plural': 'Fotos da empresa',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
