# Generated by Django 6.0.7 on 2026-07-23 22:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('cidades', '0003_alter_cidade_ativa_alter_cidade_criada_em'),
        ('empresas', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'ordering': ['-destaque', 'nome'], 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AddField(
            model_name='profissional',
            name='atendimento_domiciliar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profissional',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='bairro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profissional',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='categorias.categoria'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profissional',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profissional',
            name='endereco',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='horario',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='profissional',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profissional',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='cidades.cidade'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissionais', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(max_length=180),
        ),
        migrations.AddConstraint(
            model_name='profissional',
            constraint=models.UniqueConstraint(fields=('cidade', 'slug'), name='profissional_slug_unico'),
        ),
    ]
