# Generated by Django 6.0.7 on 2026-07-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0003_profissional_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='profissionais/galeria/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Foto do profissional',
                'verbose_name_plural': 'Fotos do profissional',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
