# Generated by Django 6.0.7 on 2026-07-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servico_profissional_empresa_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
