# Generated by Django 6.0.7 on 2026-07-24 13:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('cidades', '0003_alter_cidade_ativa_alter_cidade_criada_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('profissional', 'Profissional')], max_length=20, verbose_name='tipo de cadastro')),
                ('nome', models.CharField(max_length=180, verbose_name='nome / nome da empresa')),
                ('responsavel', models.CharField(blank=True, max_length=180, verbose_name='responsável')),
                ('especialidade', models.CharField(blank=True, max_length=180, verbose_name='especialidade')),
                ('descricao', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='descrição')),
                ('endereco', models.CharField(blank=True, max_length=220, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('horario', models.CharField(blank=True, max_length=180, verbose_name='horário de atendimento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='status')),
                ('observacao_admin', models.TextField(blank=True, verbose_name='observação administrativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_cadastro', to='categorias.categoria')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_cadastro', to='cidades.cidade')),
            ],
            options={
                'verbose_name': 'Solicitação de cadastro',
                'verbose_name_plural': 'Solicitações de cadastro',
                'ordering': ['-criado_em'],
            },
        ),
    ]
