# Generated by Django 6.0.7 on 2026-07-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('planos', '0002_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocadastro',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_cadastro', to='planos.plano', verbose_name='plano solicitado'),
        ),
    ]
