# Generated by Django 6.0.7 on 2026-07-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('destaque_busca', models.BooleanField(default=False)),
                ('destaque_perfil', models.BooleanField(default=False)),
                ('acesso_metricas', models.BooleanField(default=False)),
                ('prioridade_resultados', models.BooleanField(default=False)),
                ('selo_destaque', models.BooleanField(default=False)),
                ('limite_fotos', models.PositiveIntegerField(default=1)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ('ordem', 'preco_mensal', 'nome'),
            },
        ),
    ]
