# Generated by Django 6.0.7 on 2026-07-24 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('planos', '0001_initial'),
        ('profissionais', '0002_alter_profissional_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pendente', 'Pendente'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='ativa', max_length=20)),
                ('inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('renovacao_automatica', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='empresas.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='planos.plano')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ('-inicio', '-criada_em'),
            },
        ),
    ]
