# Generated by Django 6.0.7 on 2026-07-24 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('profissionais', '0002_alter_profissional_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(db_index=True, max_length=100, verbose_name='identificador do visitante')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='adicionado em')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='empresas.empresa')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('identificador', 'empresa'), name='favorito_empresa_unico'), models.UniqueConstraint(fields=('identificador', 'profissional'), name='favorito_profissional_unico')],
            },
        ),
    ]
